In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
sns.set_style("darkgrid")
import sklearn.linear_model


#Read file
psearch_df = pd.read_csv('Paid Search - PPC Prediction Analysis.csv')

In [5]:
psearch_df.head()

    Type      Channel   Device          Geo  Vendor  Clicks
0  Brand  Paid Search  Desktop       France  Google  106651
1  Brand  Paid Search  Desktop    Indonesia  Google   17610
2  Brand  Paid Search  Desktop  Switzerland  Google    4847
3  Brand  Paid Search  Desktop     Thailand  Google    7353
4  Brand  Paid Search  Desktop       Turkey    Bing   20318

In [20]:
psearch_df = psearch_df.join(pd.get_dummies(psearch_df['Type'],prefix="Type"))

In [21]:
psearch_df = psearch_df.join(pd.get_dummies(psearch_df['Device'],prefix="Device"))

In [22]:
psearch_df = psearch_df.join(pd.get_dummies(psearch_df['Geo'],prefix="Geo"))

In [23]:
psearch_df = psearch_df.join(pd.get_dummies(psearch_df['Vendor'],prefix="Vendor"))

In [25]:
psearch_df.describe()

,Clicks,Type_Brand,Type_Non-Brand,Device_Desktop,Device_Mobile,Device_Tablet,Device_Unknown,Geo_Arabic,Geo_Asia and Pacific,Geo_Australia,...,Geo_Spain,Geo_Sweden,Geo_Switzerland,Geo_Thailand,Geo_Turkey,Geo_United Kingdom,Geo_United States,Geo_Vietnam,Vendor_Bing,Vendor_Google
count,3.780000e+02,378.000000,378.000000,378.000000,378.000000,378.000000,378.000000,378.000000,378.000000,378.000000,...,378.000000,378.000000,378.000000,378.000000,378.000000,378.000000,378.000000,378.000000,378.000000,378.000000
mean,2.126060e+04,0.492063,0.507937,0.335979,0.333333,0.328042,0.002646,0.015873,0.023810,0.031746,...,0.031746,0.031746,0.015873,0.031746,0.031746,0.031746,0.034392,0.029101,0.455026,0.544974
std,9.046506e+04,0.500600,0.500600,0.472958,0.472029,0.470123,0.051434,0.125150,0.152657,0.175556,...,0.175556,0.175556,0.125150,0.175556,0.175556,0.175556,0.182474,0.168311,0.498633,0.498633
min,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.542500e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.417000e+03,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,9.754500e+03,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
max,1.343631e+06,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000